name: Vtex IO actions

'on':
  pull_request:

jobs:
  io-app-test:
    name: Vtex IO app test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      
      - name: Install dependencies
        run: yarn
      
      - name: Run test on every builder directory
        uses: vtex/action-io-app-test@master

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 12.x
        env:
          RUNNER_TEMP: /tmp
      
      - name: Install dependencies
        run: yarn
      
      - name: Lint project
        uses: vtex/action-lint@master
